
## 2. Understanding NumPy Arrays

### Creating NumPy Arrays

NumPy arrays are the core of the NumPy library. They are similar to lists in Python but can have any number of dimensions. Additionally, they provide fast mathematical operations, which is crucial for data analysis.

## Example : What is a common use of numpy in data analysis that requires speed?

NumPy's speed and efficiency are particularly beneficial in data analysis scenarios involving large datasets or complex mathematical operations. One common use case is Image Processing and Analysis. This task often requires handling large arrays of pixel data and performing rapid computations on them.

Suppose you have a collection of digital images, and you need to process these images for tasks such as filtering, color transformation, or feature extraction. NumPy arrays can be used to represent these images, with each pixel value stored in an array element. Due to NumPy's optimized performance, operations on these large arrays can be carried out quickly, which is essential for image processing tasks.

- Loading an Image as a NumPy Array: Convert an image file into a NumPy array. Each pixel's color data is represented as numbers in the array.
- Color Transformation: Apply transformations to the image, such as converting it to grayscale, by manipulating the array values.
- Filtering: Use mathematical operations to apply filters like blurring or edge detection.


In [ ]:
import numpy as np

# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)  # Expected Output: 1D Array: [1 2 3 4]
print([1, 2, 3, 4])


1D Array: [1 2 3 4]
[1, 2, 3, 4]


In [ ]:

# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)
# Expected Output:
# 2D Array:
# [[1 2 3]
#  [4 5 6]]

2D Array:
 [[1 2 3]
 [4 5 6]]




![Numpy arrays 1d 2d 3d](https://drive.google.com/uc?id=1Hjmqzzh2RgnaugCOm6a1L1RpLgqTOW9f)

### Array Attributes: Shape, Size, and Data Type

Understanding the structure of NumPy arrays is essential. The shape, size, and data type of an array tell you about its layout and the nature of its elements.



In [ ]:
# Array attributes
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)



**Expected Output**:
- Shape of the array, which indicates the number of elements in each dimension.
- Total number of elements in the array.
- Data type of the array elements.

### Important Concepts

- **Shape**: This attribute represents the dimensions of the array. For a 2D array, it will give you the number of rows and columns.
- **Size**: This is the total number of elements in the array.

Here are examples demonstrating different shapes and sizes of NumPy arrays:

1. **1D Array Example:**
   

In [ ]:
array_1d = np.array([1, 2, 3, 4])
   # Output: 1D Array: [1 2 3 4], Shape: (4,), Size: 4
print(array_1d)

[1 2 3 4]




2. **2D Array Example:**

Example : What is an example of when a 2D array is used?

Financial Data Analysis

Imagine you have a dataset of stock prices for different companies over several days. Each row in your dataset represents a different day, and each column represents a different company. You can use a 2D NumPy array to store and analyze this data.
For data representation, each row in the 2D array would represent stock prices for a day, and each column would represent a different company.

In [ ]:
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
   # Output:
   # 2D Array:
   # [[1 2 3]
   #  [4 5 6]]
   # Shape: (2, 3), Size: 6
print(array_2d)

[[1 2 3 4]
 [5 6 7 8]]




3. **3D Array Example:**
   

In [ ]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
   # Output:
   # 3D Array:
   # [[[1 2]
   #   [3 4]]
   #
   #  [[5 6]
   #   [7 8]]]
   # Shape: (2, 2, 2), Size: 8
print(array_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]




4. **Larger 2D Array Example:**
   

In [ ]:
array_2d_large = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
   # Output:
   # Larger 2D Array:
   # [[ 1  2  3  4]
   #  [ 5  6  7  8]
   #  [ 9 10 11 12]]
   # Shape: (3, 4), Size: 12



- **Data Type**: NumPy arrays have elements of the same data type. The `dtype` attribute tells you the type of these elements, such as `int`, `float`, etc.

| Data Type | Description |
|-----------|-------------|
| `int`     | Integer (e.g., `int16`, `int32`, `int64`) |
| `float`   | Floating-point number (e.g., `float16`, `float32`, `float64`) |
| `bool`    | Boolean (True or False) |
| `complex` | Complex number (e.g., `complex64`, `complex128`) |
| `str`     | String |
| `object`  | Python object type |

## Exercise: Exploring NumPy Arrays

1. **Inspect Attributes**: For each array you created, print its shape, size, and data type.
2. **Play with Data Types**: Create a new array with numbers from 1 to 3, but specify the data type as `float`. Check and print its data type.

**Expected Output**:
- Prints of the created arrays with their respective shapes, sizes, and data types.
- An array with a specified data type different from the default.


Exercise: Create the following arrays:

* A one dimensional array with the temperatures from this week.
* A two dimensional array of shape 2,5 with random values (choose them yourself) from 1 to 10.
* A 3D array with valid pixel values for a picture with 9 pixels.


In [ ]:
temps = np.array([21, 21, 20, 20, 21, 21, 21])

In [ ]:
vals = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(vals)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
img = [[[100, 123, 456],
        [100, 123, 456],
        [100, 123, 456]],
         [[100, 123, 456],
         [100, 123, 456],
         [100, 123, 456]],
          [[100, 123, 456],
          [100, 123, 456],
          [100, 123, 456]]]

print(img)

[[[100, 123, 456], [100, 123, 456], [100, 123, 456]], [[100, 123, 456], [100, 123, 456], [100, 123, 456]], [[100, 123, 456], [100, 123, 456], [100, 123, 456]]]
