🌟 Exercise 1 : Array Creation And Manipulation
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:



# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
import numpy as np

a1 = np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

🌟 Exercise 2 : Type Conversion And Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:

In [6]:
list_1 = [3.14, 2.17, 0, 1, 2]

a2 = np.array(list_1, dtype=int)

a2

array([3, 2, 0, 1, 2])

🌟 Exercise 3 : Working With Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
# method 1
# a = np.array([[1,2,3],[4,5,6],[7,8,9]])

a3 = np.arange(1,10)
a3 = a.reshape(3,3)
a3


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

🌟 Exercise 4 : Creating Multi-Dimensional Array With Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:



array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])

In [27]:
a4 = np.random.random(20).reshape(4,5)
a4

array([[0.71672568, 0.17352976, 0.47041453, 0.78673751, 0.20084405],
       [0.62971431, 0.73593973, 0.44051733, 0.61222598, 0.91597061],
       [0.29610489, 0.39417071, 0.10494823, 0.01841396, 0.61302492],
       [0.65306647, 0.84501379, 0.50749368, 0.60238554, 0.03097043]])

🌟 Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

Expected Output:



array([20, 21, 22, 23, 24])

In [29]:
a5 = np.array([[1,4,6,2],[4,1,6,1],[5,1,6,2]])

a5[1]

array([4, 1, 6, 1])

🌟 Exercise 6 : Reversing Elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [66]:
a6 = np.arange(10)
a6 = a6[::-1]
a6

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

🌟 Exercise 7 : Identity Matrix

Instructions
Create a 4x4 identity matrix using NumPy.

Expected Output:
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [81]:
a7 = np.zeros((4, 4), dtype=float)
a7

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
a7[[np.arange(4)],[np.arange(4)]] = a7[[np.arange(4)],[np.arange(4)]]+1



In [83]:
a7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

🌟 Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

Expected Output:

Sum: 45, Average: 4.5

In [94]:
a8 = np.arange(1,10,1)
f'Sum:{a8.sum()}, Average: {a8.mean()}'

'Sum:45, Average: 5.0'

🌟 Exercise 9 : Create Array And Change Its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [97]:
a9 = np.arange(1,21,1).reshape(4,5)
a9

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

🌟 Exercise 10 : Conditional Selection Of Values
Instructions
Extract all odd numbers from a given NumPy array.

Expected Output:

array([1, 3, 5, 7, 9])

In [99]:
a10 = np.arange(0,10)
a10odds = a10[a10%2 != 0]
a10odds

array([1, 3, 5, 7, 9])