## 4. Basic Operations with Arrays

### Array Arithmetic and Broadcasting
Broadcasting in NumPy is a powerful feature that allows for arithmetic operations between arrays of different shapes. It works by 'stretching' the smaller array to match the shape of the larger array, enabling element-wise operations. This is particularly useful when performing operations between a smaller array and a larger multidimensional array, as it avoids the need for manual array reshaping.


In [8]:
import numpy as np

# Creating sample arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)



Addition: [5 7 9]


In [7]:
# Creating sample arrays of different sizes
a = np.array([1])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)


Addition: [5 6 7]


In [9]:
# Broadcasting
print("Broadcasting with scalar:", a * 3)

Broadcasting with scalar: [3 6 9]


# Example of when it would be useful to multiply by a scalar :
Imagine you have a dataset containing measurements in a particular unit, and you need to convert these measurements to a different unit for analysis or reporting purposes. For instance, consider a scientific dataset with temperatures recorded in degrees Celsius, and you need to convert these to degrees Fahrenheit.



### Example 1: Adding a Scalar to an Array



In [10]:
# Creating a 1D array
a = np.array([1, 2, 3])

# Adding a scalar value to the array
result = a + 5

print("Original Array:", a)
print("After Adding 5:", result)

Original Array: [1 2 3]
After Adding 5: [6 7 8]




### Example 2: Combining 1D and 2D Arrays



In [11]:
# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2],
              [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)

1D Array: [0 1 2]
2D Array: [[0 1 2]
 [3 4 5]]
Broadcasted Addition: [[0 2 4]
 [3 5 7]]




### Example 3: Broadcasting Arrays with Different Shapes



In [13]:
# Creating two arrays
a = np.array([[1], [2], [3]])
b = np.array([1, 2, 3])

# Broadcast a:
# 1 1 1
# 2 2 2
# 3 3 3

#Broadcast b
# 1 2 3
# 1 2 3
# 1 2 3

# Adding the two arrays
result = a + b

print("Array a:", a)
print("Array b:", b)
print("Broadcasted Addition:", result)

# Creating two arrays
a = np.array([[1], [2], [3]])
c = np.array([7, 8, 9])

# Broadcast a:
# 1 1 1
# 2 2 2
# 3 3 3

#Broadcast b
# 7 8 9
# 7 8 9
# 7 8 9

# Adding the two arrays
result = a + c

# Result
# 8 9 10
# 9 10 11
# 10 11 12

print("Array a:", a)
print("Array b:", c)
print("Broadcasted Addition:", result)

Array a: [[1]
 [2]
 [3]]
Array b: [1 2 3]
Broadcasted Addition: [[2 3 4]
 [3 4 5]
 [4 5 6]]
Array a: [[1]
 [2]
 [3]]
Array b: [7 8 9]
Broadcasted Addition: [[ 8  9 10]
 [ 9 10 11]
 [10 11 12]]




### Example 4: Broadcasting Limitations



In [14]:
# Creating two incompatible arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])

# Broadcasting b
# 1 2 ?
# 1 2 ?

try:
    result = a + b
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (2,3) (2,) 




### Example 5: Multiplying Arrays of Different Dimensions



In [ ]:
# Creating a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

# Element-wise multiplication
result = a * b

print("2D Array:", a)
print("1D Array:", b)
print("Broadcasted Multiplication:", result)



### Array Aggregation: Sum, Mean, Min, Max
When working with multidimensional arrays, aggregation functions like `sum`, `mean`, `min`, and `max` can be applied across the entire array or along a specific axis.

- **Default Behavior:** By default, these functions aggregate over all dimensions of the array.
- **Specifying an Axis:** You can specify an axis along which to perform the aggregation. For example, in a 2D array, using `axis=0` will aggregate each column, and `axis=1` will aggregate each row.


In [15]:
# Creating a sample array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
print("Sum:", np.sum(array))

# Mean value
print("Mean:", np.mean(array))

# Minimum and Maximum
print("Min:", np.min(array), "Max:", np.max(array))

Sum: 21
Mean: 3.5
Min: 1 Max: 6


In [43]:
# # Converting Image to Grayscale example
from PIL import Image
import numpy as np
image = Image.open('soldier.png', )
arr = np.array(image)
arr.shape
res = arr.mean(axis=2)
res = res.round()

In [44]:
res = res.astype(np.uint8)

In [45]:
im = Image.fromarray(res)
im.save('out.jpg')



## Exercise: Basic Operations with Arrays

1. **Arithmetic Operations**: Create two 1D arrays of 3 elements each and perform element-wise addition, subtraction, multiplication, and division.
2. **Aggregation Functions**: For the arrays created above, find the sum, mean, minimum, and maximum of each array.
3. **Broadcasting with Scalar**: Multiply one of the arrays by a scalar (e.g., 5) and observe the result.


## In-depth Topic: Array Broadcasting Explained
Array broadcasting in NumPy refers to the ability of arrays with different shapes to participate in arithmetic operations. It's a powerful feature that allows for efficient array computations.

Example :  When would one use row-wise normalization or outer product?

- Normalizing Features in a Dataset
Suppose you have a dataset with multiple features, and each row in your array represents a different sample with various feature values.   You might want to normalize these features before feeding them into a machine learning model. This is crucial when different rows represent different data entities (like individual samples or experiments) and you want to standardize them for comparison or further analysis.

- Building a Covariance Matrix
In statistics, the covariance matrix is an important tool for understanding the relationship between different variables in a dataset. The outer product can be used to compute the covariance matrix when you have a series of observations.

![Alt text](https://drive.google.com/uc?id=161Ld7gFw163ZTb-TLMueSvN0Ah1QarV7)

## Important Statistics in NumPy: Mean, Median, Standard Deviation
- **Mean**: The average value of all elements in the array.
- **Median**: The middle value of the array when sorted.
- **Standard Deviation**: A measure of the amount of variation or dispersion in the array.

![Alt text](https://drive.google.com/uc?id=1chqKYUjHXPKcEIaIgxH7Tg_y5APb5Raq)
![Alt text](https://drive.google.com/uc?id=1cA8s-VeWuP0_svDH5ZjFk4bRVwqm2X8g)

