In [2]:
import numpy as np

In [3]:
# Create a vector* of zeros with size 10 using np.zeros().

# Example output: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

a_vector = np.zeros(10)
a_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# Compute the memory size* of any array. Note: You can do this by multiplying the length of the array 
#     by the size of one array element, which you can find using the .itemsize attribute.

# Example output: `80` (for an array of size 10 with elements of type float64)

p = np.arange(1,11).reshape(2,5)
p

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
size = p.size
itemsize = p.itemsize
itemsize*size


40

In [25]:
#Retrieve the documentation of the numpy add function from the command line.

python -c "import numpy as np; help(np.add)"


SyntaxError: invalid syntax (<ipython-input-25-b0f75e44e121>, line 1)

In [27]:
# Create a vector with values ranging from 10 to 49 using np.arange().

# Example output: [10 11 12 ... 47 48 49]

array = np.arange(10,50)
array


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [34]:
# Create a 3x3 matrix* with values ranging from 0 to 8 using np.reshape().

# Example output: [[0 1 2]
#                  [3 4 5]
#                  [6 7 8]]

matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#Find indices of non-zero elements from [1,2,0,0,4,0] using np.nonzero().

lst = [1,2,0,0,4,0]
np.nonzero


In [ ]:
🌟 Exercise 1:
Instructions
Import the numpy package under the name np.

Reverse a vector so the first element becomes last (Hint: Use slicing).

Example output: If input is [10 11 12 ... 47 48 49], 
output should be [49 48 47 ... 12 11 10]




Example output: (array([0, 1, 4]),)


Create a 3x3 identity matrix* using np.eye().

Example output: [[1. 0. 0.]
                 [0. 1. 0.]
                 [0. 0. 1.]]


Create a 5x5 matrix with row values ranging from 0 to 4. The output should be a matrix where each row is [0, 1, 2, 3, 4].

Example output: 
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Create a vector of size 10 with values ranging from 0 to 1, both excluded. You can use np.linspace.

Example output: [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 
                0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


Create a random vector of size 10 and sort it.

Example output: An array of 10 random numbers between 0 and 1, 
                sorted in ascending order.


Print the minimum and maximum representable value for each numpy scalar type* (int8, int32, int64, float32, float64). Use np.iinfo and np.finfo.

Example output: This command prints the minimum and maximum 
                representable values for the specified data types.


How to convert a float (32 bits) array into an integer (32 bits) in place? Use np.ndarray.astype.

Example output: This command converts a floating-point array 
                into an integer array, rounding towards zero.


Subtract the mean* of each row of a matrix. Use np.mean with axis=1.

Example output: This command subtracts the mean of each 
                row from each element in that row.


How to sort an array by the nth column? Use np.argsort.

Example output: This command sorts a 2D array by the nth column.


How to swap two rows of an array? You can do this using array indexing.

Example output: If the input is [[0, 1, 2], [3, 4, 5], [6, 7, 8]] 
                and you swap the first and second row, the output 
                should be [[3, 4, 5], [0, 1, 2], [6, 7, 8]].


Given an array C that is a bincount*, how to produce an array A such that np.bincount(A) == C? Use np.repeat.

Example output: This command creates an array that, when binned, matches the input array.